version: "2"
services:
  # web:
  #   build: .
  #   command: npm start
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mongo
  # mongo:
  #   image: mongo:latest
  #   container_name: "mongo"
  #   ports:
  #     - 27017:27017
  jenkins:
    image: jenkins:2.60.3
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /Users/yevhenii_ihnatenko/Desktop/jenkins:/var/jenkins_home