version: "2"
services:
  # web:
  #   build: .
  #   command: npm start
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mongo
  # mongo:
  #   image: mongo:latest
  #   container_name: "mongo"
  #   ports:
  #     - 27017:27017
  # sshdev:
  #   image: rastasheep/ubuntu-sshd:18.04
  #   ports:
  #     - "8082:22"
  #   tty: true

# Jenkins CI Docker container
  ci:
    image: jenkins:2.60.3
    user:
      root
    links:
      - sshdev
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /Users/yevhenii_ihnatenko/Desktop/jenkins:/var/jenkins_home
# ssh service for dev container
  sshdev:
    image: rastasheep/ubuntu-sshd:16.04
    ports:
      - "2222:22"